/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryIdRouteImport } from './routes/country.$id'
import { Route as CountryIdFoodFoodIdRouteImport } from './routes/country.$id.food.$foodId'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryIdRoute = CountryIdRouteImport.update({
  id: '/country/$id',
  path: '/country/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryIdFoodFoodIdRoute = CountryIdFoodFoodIdRouteImport.update({
  id: '/food/$foodId',
  path: '/food/$foodId',
  getParentRoute: () => CountryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/country/$id': typeof CountryIdRouteWithChildren
  '/country/$id/food/$foodId': typeof CountryIdFoodFoodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/country/$id': typeof CountryIdRouteWithChildren
  '/country/$id/food/$foodId': typeof CountryIdFoodFoodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/country/$id': typeof CountryIdRouteWithChildren
  '/country/$id/food/$foodId': typeof CountryIdFoodFoodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/country/$id' | '/country/$id/food/$foodId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/country/$id' | '/country/$id/food/$foodId'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/country/$id'
    | '/country/$id/food/$foodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  CountryIdRoute: typeof CountryIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$id': {
      id: '/country/$id'
      path: '/country/$id'
      fullPath: '/country/$id'
      preLoaderRoute: typeof CountryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$id/food/$foodId': {
      id: '/country/$id/food/$foodId'
      path: '/food/$foodId'
      fullPath: '/country/$id/food/$foodId'
      preLoaderRoute: typeof CountryIdFoodFoodIdRouteImport
      parentRoute: typeof CountryIdRoute
    }
  }
}

interface CountryIdRouteChildren {
  CountryIdFoodFoodIdRoute: typeof CountryIdFoodFoodIdRoute
}

const CountryIdRouteChildren: CountryIdRouteChildren = {
  CountryIdFoodFoodIdRoute: CountryIdFoodFoodIdRoute,
}

const CountryIdRouteWithChildren = CountryIdRoute._addFileChildren(
  CountryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  CountryIdRoute: CountryIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
